<?php

declare(strict_types=1);

namespace McpServer;

use McpServer\Auth\MountPath;
use RuntimeException;

/**
 * On-disk store for PDFs generated by the markdown→PDF tool.
 *
 * Files are written inside the app at `data/output/<token>/<name>.pdf`, where
 * `<token>` is an unguessable 32-hex-char directory name. That token makes the
 * file addressable by a capability URL the HTTP transport can hand back to the
 * caller (`/download/<token>/<name>.pdf`) — servable without a session, yet
 * not enumerable. The stdio transport instead reports the filesystem path.
 *
 * `data/` is gitignored and never served statically; the download route in
 * index.php is the only way to read these files over HTTP.
 */
final class PdfStore {
    /** Bytes of entropy in a file's token (16 bytes => 32 hex chars). */
    private const TOKEN_BYTES = 16;

    /** Longest slug kept from a caller-supplied filename. */
    private const MAX_SLUG = 80;

    /** Absolute path of the output directory (not created until a save). */
    public static function dir(): string {
        return dirname(__DIR__) . '/data/output';
    }

    /**
     * Persist a generated PDF under a fresh token directory.
     *
     * @param string $pdf  the raw PDF bytes
     * @param string $name caller-supplied base name (extension ignored)
     * @return array{token: string, filename: string, path: string, bytes: int}
     * @throws RuntimeException when the file cannot be written
     */
    public function save(string $pdf, string $name = 'document'): array {
        $token = bin2hex(random_bytes(self::TOKEN_BYTES));
        $dir = self::dir() . '/' . $token;
        if (!is_dir($dir) && !mkdir($dir, 0777, true) && !is_dir($dir)) {
            throw new RuntimeException("Could not create the PDF output directory: $dir");
        }

        $filename = self::slug($name) . '.pdf';
        $path = $dir . '/' . $filename;
        if (file_put_contents($path, $pdf) === false) {
            throw new RuntimeException("Could not write the PDF to $path");
        }

        return ['token' => $token, 'filename' => $filename, 'path' => $path, 'bytes' => strlen($pdf)];
    }

    /**
     * Resolve a download request to an absolute path, or null when the
     * token/filename is malformed or resolves outside the output directory
     * (path-traversal guard).
     */
    public static function resolve(string $token, string $filename): ?string {
        if (preg_match('/^[0-9a-f]{' . (self::TOKEN_BYTES * 2) . '}$/', $token) !== 1) {
            return null;
        }
        if ($filename === '' || $filename !== basename($filename)) {
            return null;
        }
        if (preg_match('/^[A-Za-z0-9._-]+\.pdf$/', $filename) !== 1) {
            return null;
        }

        $root = realpath(self::dir());
        $path = realpath(self::dir() . '/' . $token . '/' . $filename);
        if ($root === false || $path === false || !str_starts_with($path, $root . DIRECTORY_SEPARATOR)) {
            return null;
        }
        return $path;
    }

    /**
     * The download URL for a stored file, absolute and mount-aware.
     *
     * @param array<string, mixed> $server $_SERVER of the current request
     */
    public static function url(string $token, string $filename, array $server): string {
        return MountPath::origin($server) . '/download/' . $token . '/' . rawurlencode($filename);
    }

    /** A filesystem-safe slug derived from a caller-supplied name. */
    private static function slug(string $name): string {
        $base = pathinfo($name, PATHINFO_FILENAME);
        $slug = preg_replace('/[^A-Za-z0-9._-]+/', '-', $base) ?? '';
        $slug = trim($slug, '-._');
        if ($slug === '') {
            $slug = 'document';
        }
        return substr($slug, 0, self::MAX_SLUG);
    }
}